networks:
    my_network:
        name: my_network

services:
    nginx:
        build:
            context: ./dockerfiles/nginx
        container_name: nginx
        networks:
            - my_network
        ports:
            - "4000:80"
        volumes:
            - nginx_logs:/var/log/nginx
            - ./public:/var/www/html
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: ./dockerfiles/php-fpm
        container_name: php
        networks:
            - my_network
        ports:
            - "9009:9003"
        volumes:
            - php_logs:/var/log/php-fpm
            - ./:/var/www
            - ./public:/var/www/html
            - ./dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini
            # - ./dockerfiles/php-fpm/xdebug.log:/var/log/xdebug.log
        depends_on:
            - redis
            - mongo
            - prometheus
            - mysql

    redis:
        image: redis:7
        container_name: redis
        networks:
            - my_network
        volumes:
            - redis_data:/data

    mongo:
        image: mongo:7
        volumes:
            - mongo_db:/data/db
        container_name: mongo_db
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=mydatabase
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        networks:
            - my_network

    prometheus:
        image: prom/prometheus:v2.43.0
        container_name: prometheus
        volumes:
            - ./dockerfiles/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        networks:
            - my_network
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'

    prometheus_grafana:
        image: grafana/grafana:8.2.6
        container_name: prometheus_grafana
        networks:
            - my_network
        ports:
            - "3000:3000"
        volumes:
            - prometheus_grafana_data:/var/lib/grafana
            - prometheus_grafana_config:/etc/grafana
        depends_on:
            - prometheus


    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my_network
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - my_network

    supervisor:
        container_name: supervisor
        build:
            context: ./
            dockerfile: dockerfiles/supervisor/Dockerfile.supervisor
        volumes:
            - .:/var/www/html
        restart: unless-stopped
        environment:
            - APP_ROOT=/var/www/html
            - QUEUE_DRIVER=${QUEUE_CONNECTION}
            - OPTIONS=${QUEUE_OPTIONS}
            - NUM_PROCS=${NUM_PROCS}
        networks:
            - my_network
    

volumes:
    nginx_logs:
    php_logs:
    prometheus_data:
    prometheus_grafana_data:
    prometheus_grafana_config:
    redis_data:
    mongo_db:
    mongo_configdb:
    mysql_data:
