networks:
    mup_network:
        name: mup_network

services:
    mup_mobiq_product_v2_nginx:
        build:
            context: ./dockerfiles/nginx
        container_name: mup_mobiq_product_v2_nginx
        networks:
            - mup_network
        ports:
            - "4000:80"
        volumes:
            - mup_mobiq_product_v2_nginx_logs:/var/log/nginx
            - ./public:/var/www/html
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mup_mobiq_product_v2_php

    mup_mobiq_product_v2_php:
        build:
            context: ./dockerfiles/php-fpm
        container_name: mup_mobiq_product_v2_php
        networks:
            - mup_network
        environment:
            XDEBUG_MODE: develop,coverage,debug
            XDEBUG_CONFIG: client_host=host.docker.internal
        volumes:
            - mup_mobiq_product_v2_php_logs:/var/log/php-fpm
            - ./:/var/www
            - ./public:/var/www/html
            - ./dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mup_redis
            - mup_mongo
            - mup_prometheus
            - mup_graylog
            - mup_mysql

    mup_redis:
        image: redis:7
        container_name: mup_redis
        networks:
            - mup_network
        volumes:
            - mup_redis_data:/data

    mup_mongo:
        image: mongo:6
        container_name: mup_mongo
        networks:
            - mup_network
        volumes:
            - mup_mongo_db:/data/db
            - mup_mongo_configdb:/data/configdb
		environment:
			MONGO_INITDB_ROOT_USERNAME: mobiq_product_v2
			MONGO_INITDB_ROOT_PASSWORD: password

    mup_prometheus:
        image: prom/prometheus:v2.43.0
        container_name: mup_prometheus
        volumes:
            - ./dockerfiles/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - mup_prometheus_data:/prometheus
        networks:
            - mup_network
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'

    mup_prometheus_grafana:
        image: grafana/grafana:8.2.6
        container_name: mup_prometheus_grafana
        networks:
            - mup_network
        ports:
            - "3000:3000"
        volumes:
            - mup_prometheus_grafana_data:/var/lib/grafana
            - mup_prometheus_grafana_config:/etc/grafana
        depends_on:
            - mup_prometheus

    mup-elasticsearch: # Graylog doesn't support underlines as elasticsearch host
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        container_name: mup-elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - mup_network
        volumes:
            - mup_elasticsearch_data:/usr/share/elasticsearch/data

    mup_graylog:
        image: graylog/graylog:5.0
        container_name: mup_graylog
        environment:
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
            - GRAYLOG_MONGODB_URI=mongodb://mup_mongo:27017/graylog
            - GRAYLOG_ELASTICSEARCH_HOSTS=http://mup-elasticsearch:9200
            - GRAYLOG_ROOT_PASSWORD_SHA2=8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92 #123456
            - GRAYLOG_PASSWORD_SECRET=6f9efb466e043b9f3635827ce446e13c
        ports:
            - 9000:9000
        depends_on:
            - mup_mongo
            - mup-elasticsearch
        networks:
            - mup_network
        volumes:
            - mup_graylog_data:/usr/share/graylog/data

    mup_mysql:
        image: mysql:8.0
        container_name: mup_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mobiq_product_v2
            MYSQL_USER: product_v2
            MYSQL_PASSWORD: password
        volumes:
            - mup_mysql_data:/var/lib/mysql
        networks:
            - mup_network
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"


volumes:
    mup_mobiq_product_v2_nginx_logs:
    mup_mobiq_product_v2_php_logs:
    mup_prometheus_data:
    mup_prometheus_grafana_data:
    mup_prometheus_grafana_config:
    mup_redis_data:
    mup_mongo_db:
    mup_mongo_configdb:
    mup_graylog_data:
    mup_elasticsearch_data:
    mup_mysql_data:
