FROM php:8.3-fpm

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-openssl-dev \
    unzip \
    git

# Clean apt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP Extensions
RUN pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pcntl

# Install MongoDB
RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

# Install MySQL
RUN docker-php-ext-install pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy files
COPY . /var/www

# Set the working directory
WORKDIR /var/www

COPY php.ini /usr/local/etc/php/php.ini
